Deeplearning via ANN

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [5]:
tf.__version__

'2.15.0'

In [6]:
 dataset = pd.read_excel('/content/Dataset_master.xlsx', sheet_name = 'American Express User Exit Pred')
 x = dataset.iloc[:, 0:-1].values
 y = dataset.iloc[:, -1].values

In [7]:
print(x)


[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Encoding categorical data

In [8]:
#Gender Column : Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
print(x)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [10]:
#onehotencoding for location column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting dataset into training and testing

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# ANN

In [14]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

### Adding Secong Layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

### Output layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## ANN Training

### Compiling ANN

In [24]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training on Training Dataset

In [25]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
249/249 [==============================] - 3s 3ms/step - loss: 0.6207 - accuracy: 0.7010
Epoch 2/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.7864
Epoch 3/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4524 - accuracy: 0.7955
Epoch 4/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4433 - accuracy: 0.7989
Epoch 5/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4392 - accuracy: 0.8010
Epoch 6/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4367 - accuracy: 0.8030
Epoch 7/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4348 - accuracy: 0.8014
Epoch 8/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4327 - accuracy: 0.8025
Epoch 9/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4308 - accuracy: 0.8041
Epoch 10/100
249/249 [==============================] - 1s 2ms/step - loss: 0.4281 - accura

# Predicting

## Single Prediction

In [26]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 353ms/step
[[False]]


In [27]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


## Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   60]
 [ 237  176]]


0.850453172205438